config/routes.rb
Rails.application.routes.draw do
  resources :domains, except: [:show] do
    get '/index', to: 'domains#start_indexing', on: :member
  end

  root to: 'search#index'
  get '/search', to: 'search#results'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  validates :url, presence: true, uniqueness: true

  has_many :indexed_pages

  def indexed?
    status == 'indexed'
  end
end

app/models/indexed_page.rb
class IndexedPage < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :domain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    @domains = Domain.all
    @indexed, @not_indexed = @domains.partition(&:indexed?)
  end

  def new
    # Just render the template, nothing special to be seen here...
  end

  def create
    @domain = Domain.create domain_params
    redirect_to domains_path
  end

  def edit
    @domain = Domain.find params[:id]
  end

  def update
    @domain = Domain.find params[:id]
    @domain.update domain_params.merge last_indexed_at: nil, status: :not_indexed

    redirect_to domains_path
  end

  def destroy
    @domain = Domain.find params[:id]
    @domain.delete

    redirect_to domains_path
  end

  def start_indexing
    @domain = Domain.find params[:id]
    @domain.update status: :enqueued,
                   last_indexed_at: DateTime.now

    IndexDomainJob.perform_later @domain

    redirect_to domains_path
  end

  private

  def domain_params
    params.require(:domain).permit(:url)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @indexed_domains = Domain.where(status: :indexed).count
  end

  def results
    @query = params[:query]
    @results = IndexedPage.search(params[:query])
                          .page(params[:page])
                          .per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domain_helper.rb
module DomainHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/domains/edit.html.erb
<div class="card">
  <div class="card-content">
    <div class="row">
      <div class="col s12 m8">
        <h5>
          <a href="<%= domains_path %>" class="grey-text" style="margin-right: 1rem"><i class="material-icons md">arrow_back</i></a>
          Upravit doménu <%= @domain.url %>
        </h5>
      </div>
      <%= form_with url: domain_path(@domain), method: :patch do %>
        <div class="col s12">
          <div class="input-field">
            <%= label_tag "URL adresa kořenového adresáře" %>
            <%= text_field :domain, :url, autofocus: true, autocomplete: false %>
            <span class="helper-text">Při uložení změn dojde k odstranění záznamů z indexu</span>
          </div>
        </div>
        <div class="col s12">
          <%= submit_tag "Uložit změny", class: 'btn-large blue-grey' %>
          <%= link_to "Smazat tuto doménu", domain_path(@domain), method: :delete, class: 'btn-large red', data: { confirm: "Tato akce je nevratná." } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/domains/index.html.erb
<div class="card">
  <div class="card-content">
    <div class="row">
      <div class="col s12 m8">
        <h5>Správa domén</h5>
        <p class="grey-text">Celkem je v systému <%= @domains.count %> nastavených domén</p>
      </div>
      <div class="col s12 m4">
        <%= link_to "Přidat doménu", new_domain_path, class: 'right btn green' %>
      </div>
    </div>
    <% unless @not_indexed.empty? %>
      <h5>Domény, které ještě nebyly indexované.</h5>
      <% @not_indexed.each do |domain| %>
        <div class="card">
          <div class="card-content">
            <img src="https://s2.googleusercontent.com/s2/favicons?domain=<%= domain.url %>"><br>
            <code class="black-text"><%= domain.url %></code><br>
            <% case domain.status %>
            <% when 'enqueued' %>
              <small class="grey-text">Čeká ve frontě na indexování</small>
            <% when 'being_indexed' %>
              <small class="blue-text">Probíhá indexování domény</small>
            <% when 'error' %>
              <small class="red-text">Při indexování došlo k chybě!</small>
            <% end %>

            <br>
            <small id="domain_<%= domain.id %>"></small>
          </div>
          <div class="card-action">
            <%= link_to 'Upravit', edit_domain_path(domain), class: 'black-text' %>
            <% unless %w[being_indexed enqueued].include? domain.status %>
              <%= link_to 'Indexovat', domain_path(domain) + '/index', class: 'red-text' %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @indexed.empty? %>
      <h5>Domény v indexu</h5>
      <% @indexed.each do |domain| %>
        <div class="card">
          <div class="card-content">
            <img src="https://s2.googleusercontent.com/s2/favicons?domain=<%= domain.url %>"><br>
            <code class="black-text"><%= domain.url %></code><br>
            <small class="grey-text">Naposledy indexováno <b><%= domain.last_indexed_at.to_s(:long) %></b></small>
          </div>
          <div class="card-action">
            <%= link_to 'Upravit', edit_domain_path(domain), class: 'black-text' %>
            <%= link_to 'Indexovat znovu', domain_path(domain) + '/index', class: 'black-text' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <script>
      $(document).on('turbolinks:load', function () {
          if (window.location.href === "<%= domains_url %>") {
              // Load the action cable connection
              enableDomainStatusUpdatesChannel();
          }
      });
  </script>
</div>

app/views/domains/new.html.erb
<div class="card">
  <div class="card-content">
    <div class="row">
      <div class="col s12 m8">
        <h5>
          <a href="<%= domains_path %>" class="grey-text" style="margin-right: 1rem"><i class="material-icons md">arrow_back</i></a>
          Přidat novou doménu
        </h5>
      </div>
      <%= form_with url: domains_path, method: :post do %>
        <div class="col s12">
          <div class="input-field">
            <%= label_tag "URL adresa kořenového adresáře" %>
            <%= text_field :domain, :url, autofocus: true %>
          </div>
        </div>
        <div class="col s12">
          <%= submit_tag "Přidat do systému", class: 'btn-large blue-grey' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webový vyhledávač</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
</head>

<body>
<nav class="blue-grey">
  <div class="nav-wrapper">
    <div class="container">
      <a href="<%= root_path %>" class="brand-logo">Webový vyhledávač</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="<%= root_path %>">Vyhledávání</a></li>
        <li><a href="<%= domains_path %>">Správa domén</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container app-container">
  <%= yield %>
</div>
</body>
</html>

app/views/search/index.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card" style="margin-top: 3rem;">
      <div class="card-content">
        <%= form_with url: search_path, remote: true, method: :get do %>
          <div class="row">
            <div class="input-field col s12">
              <%= label_tag :query, 'Hledaný výraz' %>
              <%= text_field_tag :query, nil, autofocus: true, required: true, minlength: 3 %>
              <small class="helper-text">Prohledává se <%= @indexed_domains %> domén</small>
            </div>
            <div class="col s12">
              <div class="center">
                <%= button_tag 'Hledat', name: nil, class: 'btn-large blue-grey aves-effect waves-light' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/results.html.erb
<div class="card">
  <div class="card-content">
    <div class="card-title">Výsledky pro <b>&bdquo;<%= @query %>&rdquo;</b></div>
    <div class="col s12">
      <div class="valign-wrapper" style="margin-bottom: 1rem;">
        <%= link_to_prev_page @results, 'arrow_back', class: 'grey-text material-icons' %>
        <b style="margin: 0 1.5rem">
          Strana <%= @results.current_page %>
        </b>
        <%= link_to_next_page @results, 'arrow_forward', class: 'grey-text material-icons' %>
      </div>
    </div>

    <div class="row">
      <% @results.each do |result| %>
        <div class="col s12">
          <a href="<%= result.url %>" target="_blank">
            <div class="card hoverable">
              <div class="card-content">
                <img src="https://s2.googleusercontent.com/s2/favicons?domain=<%= result.url %>">
                <h6 class="black-text"><%= result.title %></h6>
                <small><%= result.url %></small>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>